# Your Solution
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
  labels:
    app: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: s224021028acr.azurecr.io/pavan-jarjana-sit722-part5-book_catalog:d04809ad80cb2a924fb5072d7bc708b0f405a945
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: postgresql://s224021028:admin-roy97@s224021028apdb.postgres.database.azure.com:5432/postgres
        command: ["uvicorn"]
        args: ["app.main:app", "--host", "0.0.0.0", "--port", "8000"]
---
apiVersion: v1
kind: Service
metadata:
  name: bcs
spec:
  selector:
    app: book-catalog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
  labels:
    app: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: s224021028acr.azurecr.io/pavan-jarjana-sit722-part5-inventory_management:d04809ad80cb2a924fb5072d7bc708b0f405a945
        ports:
        - containerPort: 8001
        env:
        - name: DATABASE_URL
          value: postgresql://s224021028:admin-roy97@s224021028apdb.postgres.database.azure.com:5432/postgres
        command: ["uvicorn"]
        args: ["app.main:app", "--host", "0.0.0.0", "--port", "8001"]
---
apiVersion: v1
kind: Service
metadata:
  name: ims
spec:
  selector:
    app: inventory-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: LoadBalancer