name: Deploy microservices to AKS

on:
  push: 
    branches:
      - main
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERSION: latest
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: bash ./scripts/build-image.sh
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup infrastructure
        run: bash ./scripts/terraform.sh

      - name: Azure Login via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Publish
        run: |
          ACR_PASSWORD=$(az acr credential show --name ${{ secrets.CONTAINER_REGISTRY }} --query "passwords[0].value" --output tsv)
          echo "REGISTRY_PASSWORD=${ACR_PASSWORD}" >> $GITHUB_ENV
          bash ./scripts/push-image.sh

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER }}
      
      - name: Install kubectl
        run: sudo az aks install-cli
      
      - name: Deploy
        run: bash ./scripts/deploy.sh