name: Deploy microservices to AKS

on:
  push: 
    branches:
      - main
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PASSWORD }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: chmod +x ./scripts/build-image.sh

      - name: Azure Login via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Publish
        run: chmod +x ./scripts/push-image.sh

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER }}
      
      - uses: tale/kubectl-action@v1
      
      - name: Deploy
        run: chmod +x ./scripts/deploy.sh